{"author": {}, "body": "[deleted]", "created_utc": 1586024790.0, "distinguished": null, "id": "fmfd6zw", "is_submitter": false, "link_id": "t3_fuy9mr", "parent_id": "t3_fuy9mr", "score": -15, "stickied": false, "subreddit_id": "t5_2sjnq", "downs": 0, "total_awards_received": 0, "edited": 1586046360.0, "name": "t1_fmfd6zw", "collapsed": false, "permalink": "/r/TechNewsToday/comments/fuy9mr/no_5g_didnt_cause_the_coronavirus_pandemic/fmfd6zw/"}