{"author": {}, "body": "[deleted]", "created_utc": 1586245213.0, "distinguished": null, "id": "fmo4mo7", "is_submitter": false, "link_id": "t3_fuy9mr", "parent_id": "t1_fmo4297", "score": 1, "stickied": false, "subreddit_id": "t5_2sjnq", "downs": 0, "total_awards_received": 0, "edited": 1586245485.0, "name": "t1_fmo4mo7", "collapsed": false, "permalink": "/r/TechNewsToday/comments/fuy9mr/no_5g_didnt_cause_the_coronavirus_pandemic/fmo4mo7/"}